### ISSUE TITLE
Partials and layouts are not migrated

### ISSUE THREAD

**Issue by smcyr** [statamic/migrator#11]
Partials and layouts are not migrated to the new resources/views folder.
Also, I have a view `default.antlers.html` but when I visit the homepage, I have this error:
`View [home] not found.`

**Comment by vladdu** [comment]
The ThemeMigrator only looks for templates. It's relatively easy to make it look into the layouts and partials folders, but what is a good way to structure the resulting files? Names will clash (especially "default"). Changing the name requires modifying all contents that references it, so I suggest that the migrator will output messages like "Rename references to layout 'default' as 'layout_default'" or something similar.

**Comment by smcyr** [comment]
Could they not be included into "views/layouts" and "views/partials" folder with a message that you can restructure it as you see fit?

**Comment by jasonvarga** [comment]
Yup.

And your view home not found error would be because the home entry has `template: home` in it.
