### ISSUE TITLE
Error on migrate:fieldset-partial

### ISSUE THREAD

**Issue by thinkingcap** [statamic/migrator#111]
Using the following...
php please migrate:fieldset-partial blurb

ERROR  Command "migrate:fieldset-partial" is not defined. Did you mean one of these?

**Comment by jasonvarga** [comment]
This was removed intentionally, but we forgot to remove it from the readme.

Are you actually needing this or were you just running all the commands you saw in the readme?

**Comment by thinkingcap** [comment]
When first trying migrate:site I would get the error "Fieldtype expected a single value but encountered an array." 
and wasnt able to track down the source so I started migrating piecemeal.
Doing the migration piecemeal has actually worked for me so far.

**Comment by jesseleite** [comment]
>When first trying migrate:site I would get the error "Fieldtype expected a single value but encountered an array."

Curious if you could show that error? The `migrate:site` command should log exception stack traces to `site-migration-log-{$timestamp}.yaml` in your site root.

**Comment by thinkingcap** [comment]
The error mentioned was encountered when logging into the CP. The migrate:site command itself didnt throw any errors.

**Comment by jesseleite** [comment]
@thinkingcap Gotcha! I did remove the `migrate:fieldset-partial` section from the readme to prevent future confusion. Hope all is going well with your migrations!
