### ISSUE TITLE
Setting migrations fail

### ISSUE THREAD

**Issue by stvnthomas** [statamic/migrator#117]
I'm migrating from a v2 site to v5 but it's unable to complete due to some errors when migrating settings:

```
Settings exception: assets
The command "'/REDACTED/vendor/statamic/migrator/src/../vendor/bin/php-cs-fixer' 'fix' '/PROJECT_PATH/config/statamic/assets.php' '--rules' '{"@PSR2":true,"array_indentation":true,"array_syntax":{"syntax":"short"},"trailing_comma_in_multiline":{"elements":["arrays"]},"binary_operator_spaces":true}'" failed.

Working directory: REDACTED

Error: proc_open(): posix_spawn() failed: No such file or directory
```

The path to `php-cs-fixer` is incorrect and seems to stem from a695b45. The migration is able to complete when I revert the change.

**Comment by jesseleite** [comment]
Whoops yep! Should be fixed now, if you composer update statamic/migrator to latest 👍
