### ISSUE TITLE
Field types in blueprints not migrated

### ISSUE THREAD

**Issue by smcyr** [statamic/migrator#12]
Some field types in blueprints were not modified for the new types:

- [ ] `type: page` is now `type: entries`
- [ ] `type: collection` is now `type: entries`
- [ ] `type: partial && fieldset: ___` is now `import: ___`, see issue https://github.com/statamic/cms/issues/951

**Comment by jesseleite** [comment]
Thanks for reporting! Closing this as they've been added to the roadmap in #4, just to keep it all in one place.
