### ISSUE TITLE
Some fieldsets should not be changed to blueprints

### ISSUE THREAD

**Issue by smcyr** [statamic/migrator#14]
I'm not sure if it's possible, but I have some fieldsets that are just used in other blueprints and those should not be changed to blueprints. See the issue https://github.com/statamic/migrator/issues/12 with the type partial that is now an import of fieldsets.

**Comment by jasonvarga** [comment]
Fieldset partials are not currently supported by the migrator (as you've noticed).

We're aware and have it tracked in #4
