### ISSUE TITLE
Taxonomies folder is required

### ISSUE THREAD

**Issue by a47ae** [statamic/migrator#15]
When attempting to migrate a v2 site without taxonomies the migrate script fails with

```
The "/path/to/statamic/site/content/taxonomies" directory does not exist. 
```
A simple `mkdir -p site/content/taxonomies` resolved the issue

**Comment by jesseleite** [comment]
@a47ae, I believe this is fixed by https://github.com/statamic/migrator/commit/c283f1f74227115194598ecf44774da723189ba3.  You should be able to `composer update` and rerun.
