### ISSUE TITLE
Error migrating settings

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/migrator#16]
statamic/cms              dev-master 0c4048e Statamic CMS
statamic/migrator         dev-master fb16f40

php please migrate:settings

In Filesystem.php line 250:

  copy(/mysitefolder/vendor/statamic/migrator/src/Concerns/../../vendor/bin/php-cs-fixer.bat): failed to open stream: No such file or directory

**Comment by jimblue** [comment]
Having the same kind of error:

```bash
In Filesystem.php line 250:

  copy(/Users/jimblue/Sites/statamic3/vendor/statamic/migrator/src/Concerns/../../vendor/bin/php-cs-fixer.bat): failed to open stream: No such file or directory
```

**Comment by jesseleite** [comment]
Should be fixed.  Trying a `composer update` and run again!

**Comment by jimblue** [comment]
migration completed 🎉 thank you 👍
