### ISSUE TITLE
Error when site contains no locale in system config

### ISSUE THREAD

**Issue by austenc** [statamic/migrator#18]
Getting an error `Undefined index: locales` when running `please migrate:site` on a site that doesn't have any locales defined in the `system.yaml` file. 

If you change this line 
https://github.com/statamic/migrator/blob/master/src/SettingsMigrator.php#L96

to `$sites = collect($system['locales'] ?? null)` it is "fixed", but perhaps a better default should be used?

**Comment by jesseleite** [comment]
The starter site ships with [this default](https://github.com/statamic/statamic/blob/master/config/statamic/sites.php), and the same default gets restored when you `php please site:clear`, so I think `$system['locales'] ?? []` is fine in this case.  Good find, thanks!

**Comment by austenc** [comment]
👍 Thanks Jesse!
