### ISSUE TITLE
Theme migration: css and js

### ISSUE THREAD

**Issue by vladdu** [statamic/migrator#19]
Is the plan that the css and js and the build scripts will be somehow migrated too? Right now (or more precisely, yesterday morning, as things maybe evolve fast), I had to do that manually.

**Comment by jasonvarga** [comment]
IMO this should be a manual thing since there's not really a standard way to set up your front-end build system.

**Comment by vladdu** [comment]
Ok. Should "php please site:clear" delete the corresponding files, you think?

**Comment by jasonvarga** [comment]
If the migrator didn't migrate those files in the first place, what would there be to clear?

**Comment by vladdu** [comment]
Right, site:clear is a normal 'please' command, not part of the migrator. I will move my questions there. Thanks!
