### ISSUE TITLE
FormMigrator throws exception when migrating demo content from v2

### ISSUE THREAD

**Issue by sluther** [statamic/migrator#22]
When migrating the demo content from v2, the FormMigrator throws an exception when migrating the contact form because there are no `columns` defined on the form. From looking at the code, it seems like this should actually check for `fields` instead.

I know that there is no demo content in v3, but I think this is still a bug in the migrator itself, since someone may have kept the contact form from the demo content.

**Comment by jesseleite** [comment]
Whoops, good find 👍
