### ISSUE TITLE
Migrating site with env:APP_URL set as the url for a locale results in a 404 error

### ISSUE THREAD

**Issue by sluther** [statamic/migrator#24]
When trying to view the homepage in the browser for a site that has `env:APP_URL` as the url for the default locale, a 404 error is displayed. This is due to the `Str::removeLeft` method prepending the URL with a / when it can't find `env:APP_URL` in the URL request string.

**Comment by jesseleite** [comment]
Don't think this is related to the migrator, unless I'm misunderstanding?

**Comment by jasonvarga** [comment]
Sounds like he had `url: "{env:APP_URL}"` in his system.yaml.

I'm not sure how the migrator would translate that over to the php version in v3.

It should be `'url' => env('APP_URL')` in sites.php. Then make sure that the APP_URL is in your v3 project's .env file.

**Comment by jesseleite** [comment]
Ah yep, good find thanks! 👌
