### ISSUE TITLE
Out of memory when referencing non-existent form

### ISSUE THREAD

**Issue by vladdu** [statamic/migrator#28]
The migrator doesn't handle forms yet. I have a collection where one of the entries contains a form. If i try to render the collection, there is an exception " Form with handle [xxx] cannot be found". The problem is that the parser gets out of memory trying to render the exception view, it looks like it gets into an endless loop or something, at /vendor/statamic/cms/src/View/Antlers/Parser.php:1405. (Adding some extra logging shows that there are very of those exceptions being handled).

I would suggest that there should be a more graceful handling of this situation (the user only sees an error 500).

**Comment by jackmcdade** [comment]
Moving this to the migrator repo.

**Comment by jesseleite** [comment]
After running the migrator, do you see the newly migrated yaml config file in `/resources/forms`, as well as it's corresponding blueprint in `/resources/blueprints`?

**Comment by jesseleite** [comment]
PS. I'm just realizing this issue is from November.  I don't think form migration was fleshed out until afterwards.  Curious if this is still an issue if you `composer update` to the latest migrator?

**Comment by jesseleite** [comment]
Closing this.  Feel free to reopen if still an issue, thanks 🙂

**Comment by jesseleite** [comment]
Closing this.  Feel free to reopen if still an issue, thanks 🙂
