### ISSUE TITLE
v2 type suggest is not migrated properly

### ISSUE THREAD

**Issue by joroe** [statamic/migrator#32]
I would expect to see
- searchable: true in the migration for suggest
- push_tags: true for create: true
- taggable: true and multiple: true because that can be inferred from a v2 suggest, right?

v2
`tags:
        type: suggest
        display: 'Tags'
        create: true
        options:
          Quarterly: Quarterly
          Vorlage: Vorlage
          'Schneller Schlau': 'Schneller Schlau'
          Magazin: Magazin
          Woche: Woche`

migrated
`handle: tags
        field:
          type: select
          display: Tags
          create: true
          options:
            Quarterly: Quarterly
            Vorlage: Vorlage
            'Schneller Schlau': 'Schneller Schlau'
            Magazin: Magazin
            Woche: Woche`

**Comment by jesseleite** [comment]
Thanks for reporting!  Closing this as suggest fieldtype migration is not yet finished (see our general roadmap in #4).
