### ISSUE TITLE
Fieldtype [partial] not found after migrating

### ISSUE THREAD

**Issue by matrad** [statamic/migrator#36]
After Migrating a Page I see the issue `Fieldtype [partial] not found (View: vendor/statamic/cms/resources/views/collections/show.blade.php)`

![Bildschirmfoto 2020-03-22 um 11 43 42](https://user-images.githubusercontent.com/660903/77247531-6660b580-6c32-11ea-8ae2-40e77b13a8fb.png)

**Comment by matrad** [comment]
If you like to reproduce the error I also can send you (privately) my statamic page.

**Comment by jesseleite** [comment]
Thanks for reporting!  Closing this as partial field migration is not yet finished (see our general roadmap in #4).
