### ISSUE TITLE
Migrator fails when there are arrays in your fieldset conditions

### ISSUE THREAD

**Issue by edalzell** [statamic/migrator#37]
Getting this error when I migrate a site:

```
Exception trace:
  at /Users/erin/Sites/simple-v3/vendor/laravel/framework/src/Illuminate/Support/Str.php:321
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at n/a:n/a
 mb_strtolower() at /Users/erin/Sites/simple-v3/vendor/laravel/framework/src/Illuminate/Support/Str.php:321
 Illuminate\Support\Str::lower() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:176
 Statamic\Migrator\FieldsetMigrator->Statamic\Migrator\{closure}() at n/a:n/a
 array_map() at /Users/erin/Sites/simple-v3/vendor/laravel/framework/src/Illuminate/Support/Collection.php:638
 Illuminate\Support\Collection->map() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:177
 Statamic\Migrator\FieldsetMigrator->migrateFieldConditions() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:128
 Statamic\Migrator\FieldsetMigrator->migrateFieldConfig() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:103
 Statamic\Migrator\FieldsetMigrator->migrateField() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:87
 Statamic\Migrator\FieldsetMigrator->Statamic\Migrator\{closure}() at n/a:n/a
 array_map() at /Users/erin/Sites/simple-v3/vendor/laravel/framework/src/Illuminate/Support/Collection.php:638
 Illuminate\Support\Collection->map() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:88
 Statamic\Migrator\FieldsetMigrator->migrateFields() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:72
 Statamic\Migrator\FieldsetMigrator->Statamic\Migrator\{closure}() at n/a:n/a
 array_map() at /Users/erin/Sites/simple-v3/vendor/laravel/framework/src/Illuminate/Support/Collection.php:638
 Illuminate\Support\Collection->map() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:73
 Statamic\Migrator\FieldsetMigrator->migrateSections() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:56
 Statamic\Migrator\FieldsetMigrator->migrateToBlueprintSchema() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/FieldsetMigrator.php:26
 Statamic\Migrator\FieldsetMigrator->migrate() at /Users/erin/Sites/simple-v3/vendor/statamic/migrator/src/Commands/MigrateSite.php:324
```

The offender:

```
        show_when:
          recurrence:
            - daily
            - weekly
            - monthly
            - every
```

**Comment by jaredchesebro** [comment]
Similar error message when I run import. 

`mb_strtolower() expects parameter 1 to be string, array given`

`Exception trace:
  at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Support/Str.php:321
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at n/a:n/a
 mb_strtolower() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Support/Str.php:321
 Illuminate\Support\Str::lower() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:176
 Statamic\Migrator\FieldsetMigrator->Statamic\Migrator\{closure}() at n/a:n/a
 array_map() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Support/Collection.php:638
 Illuminate\Support\Collection->map() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:177
 Statamic\Migrator\FieldsetMigrator->migrateFieldConditions() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:128
 Statamic\Migrator\FieldsetMigrator->migrateFieldConfig() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:103
 Statamic\Migrator\FieldsetMigrator->migrateField() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:87
 Statamic\Migrator\FieldsetMigrator->Statamic\Migrator\{closure}() at n/a:n/a
 array_map() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Support/Collection.php:638
 Illuminate\Support\Collection->map() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:88
 Statamic\Migrator\FieldsetMigrator->migrateFields() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:72
 Statamic\Migrator\FieldsetMigrator->Statamic\Migrator\{closure}() at n/a:n/a
 array_map() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Support/Collection.php:638
 Illuminate\Support\Collection->map() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:73
 Statamic\Migrator\FieldsetMigrator->migrateSections() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:56
 Statamic\Migrator\FieldsetMigrator->migrateToBlueprintSchema() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/FieldsetMigrator.php:26
 Statamic\Migrator\FieldsetMigrator->migrate() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/Commands/MigrateSite.php:324
 Statamic\Migrator\Commands\MigrateSite->Statamic\Migrator\Commands\{closure}() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/Commands/MigrateSite.php:351
 Statamic\Migrator\Commands\MigrateSite->tryMigration() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/Commands/MigrateSite.php:323
 Statamic\Migrator\Commands\MigrateSite->runMigratorOnHandle() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/Commands/MigrateSite.php:121
 Statamic\Migrator\Commands\MigrateSite->Statamic\Migrator\Commands\{closure}() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php:176
 Illuminate\Support\Collection->each() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/Commands/MigrateSite.php:122
 Statamic\Migrator\Commands\MigrateSite->migrateFieldsets() at /Volumes/MC2dev/localhost/challenge.local/vendor/statamic/migrator/src/Commands/MigrateSite.php:92
 Statamic\Migrator\Commands\MigrateSite->handle() at n/a:n/a
 call_user_func_array() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Container/Util.php:36
 Illuminate\Container\Util::unwrapIfClosure() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90
 Illuminate\Container\BoundMethod::callBoundMethod() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34
 Illuminate\Container\BoundMethod::call() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Container/Container.php:590
 Illuminate\Container\Container->call() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Console/Command.php:134
 Illuminate\Console\Command->execute() at /Volumes/MC2dev/localhost/challenge.local/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
 Illuminate\Console\Command->run() at /Volumes/MC2dev/localhost/challenge.local/vendor/symfony/console/Application.php:1001
 Symfony\Component\Console\Application->doRunCommand() at /Volumes/MC2dev/localhost/challenge.local/vendor/symfony/console/Application.php:271
 Symfony\Component\Console\Application->doRun() at /Volumes/MC2dev/localhost/challenge.local/vendor/symfony/console/Application.php:147
 Symfony\Component\Console\Application->run() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Console/Application.php:93
 Illuminate\Console\Application->run() at /Volumes/MC2dev/localhost/challenge.local/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:131
 Illuminate\Foundation\Console\Kernel->handle() at /Volumes/MC2dev/localhost/challenge.local/please:37`

**Comment by jesseleite** [comment]
Yes good call.  Closing this issue as I've added to #4.
