### ISSUE TITLE
Migrator didn't migrate our partials into fieldsets, etc

### ISSUE THREAD

**Issue by edalzell** [statamic/migrator#38]
Sorry for the vague report, but we have a complex site builder that didn't port fieldsets well.

We can provide our fieldsets privately to help debug.

**Comment by jesseleite** [comment]
I'd like to know more... but before we address this in the migrator, there may be some changes coming to fieldset yaml structure, to better match blueprint yaml structure.  Going to leave this open for now 👍

**Comment by jesseleite** [comment]
It should now migrate partial fieldsets using [the new fieldset format](https://github.com/statamic/cms/pull/1707).  Going to close this, but feel free to re-open if you’re still having issues!
