### ISSUE TITLE
migrate:site fails when /site/settings/formsets folder does not exist

### ISSUE THREAD

**Issue by benfurfie** [statamic/migrator#50]
I have a v2 site that does not have any formsets, and so doesn't have the folder in the structure. Running `php please migrate:site` runs fine until it hits the missing formset folder.

It might be worth adding an exclusion that skips folders that don't exist, but logs out the folders that weren't migrated so we can go back and check manually.

**Comment by benfurfie** [comment]
Adding the folder and re-running allows the migrator to complete, so it's definitely just a case of adding either an array of folders that can be skipped, or having a function that runs before the migrator and flags up any missing folders.

**Comment by jesseleite** [comment]
Weird, can't reproduce here 🤔
