### ISSUE TITLE
Add .php_cs.cache to .gitignore

### ISSUE THREAD

**Issue by brendanfalkowski** [statamic/migrator#57]
I noticed after running the migration this file gets generated. I'm new to it, but it looks like it's commonly added to .gitignore so maybe that should be part of Statamic's core.

Edit: I see this is actually ignored in THIS repo, but I meant it should be part of the default gitignore when you use Composer to start a new Statamic project.

**Comment by jesseleite** [comment]
👍  Not a bad idea, done! https://github.com/statamic/statamic/commit/9b3733c41b939c7903cbb1b91b7fd3133c5c83f5
