### ISSUE TITLE
Migration issues with blueprints

### ISSUE THREAD

**Issue by fitzage** [statamic/migrator#58]
My initial migration didn’t throw any errors regarding migrating fieldsets to blueprints, but I quickly discovered that it didn’t migrate most of my custom page blueprints.

I manually ran `php please migrate:fieldset` for each of the missing blueprints, and it migrated them to fieldsets instead of blueprints. Dropping them into blueprints worked successfully.

The initial migration migrated every blueprint for collections other than pages, but for my pages it only migrated default and home.

**Comment by jasonvarga** [comment]
Were those missing fieldsets ever actually used in your pages?

e.g. Was this in any page?

```
fieldset: one_of_the_missing_ones
```

**Comment by fitzage** [comment]
Yes, all of them were used on pages

**Comment by jesseleite** [comment]
👍  Will take a look, thanks!

**Comment by smcyr** [comment]
I have the exact same problem, not all page fieldsets were migrated to blueprints, only default and homepage.

**Comment by fitzage** [comment]
For the record, this happened on my second site that I’m migrating also.

**Comment by jesseleite** [comment]
Sorry for the delay on this one, should be fixed now! Let us know if any of you are still having these issues on any of your migrations after those latest updates.
