### ISSUE TITLE
migrating content from multilingual site disconnects them

### ISSUE THREAD

**Issue by verybigelephants** [statamic/migrator#63]
when migrating a statamic with existing multilingual content it correctly migrates them to their respective languages, **but** disconnects them

for example, when you go editing one article that had a translation, migrated statamic 3 website does not know that this article has a neighboring article with same originating id in the other language and acts as an article with single language (the translated article is missing the `origin` in the `.md` file

**Comment by jesseleite** [comment]
Interesting multisite issues here.  Will take a look soon!  Thanks!

**Comment by edalzell** [comment]
it also does not migrate the other sites' structures, only the default/first one.

**Comment by edalzell** [comment]
And in the collection's `.yaml` it's missing a nesting by site.

I.e. I had this:

```
structure:
  root: true
  tree:
    -
      entry: 73410e00-9cb6-4aff-b0b9-24c26d57093d
```

instead of this:
```
structure:
  root: true
  tree:
    default:
      -
        entry: 73410e00-9cb6-4aff-b0b9-24c26d57093d```

**Comment by adnankussair** [comment]
@jesseleite Really needed this to work right now... onwards to manually fixing the page structures of /ar <sigh>

**Comment by jesseleite** [comment]
@adnankussair that sigh... sigh.

Anyway, believe it should be fixed with that last update. Let us know if any of you are still running into trouble.

**Comment by adnankussair** [comment]
@jesseleite hahaha

Thanks Brotha. I'm sure we'll be testing this again shortly. But thankfully we got things manually sorted with the help of some google translate...
