### ISSUE TITLE
`migrate:site` is not defined

### ISSUE THREAD

**Issue by andyra** [statamic/migrator#66]
I'm folling the migration instructions for a fresh Statamic install and I'm getting the following error:

```
Command "migrate:site" is not defined.
Did you mean one of these?
      migrate
      migrate:fresh
      migrate:install
      migrate:refresh
      migrate:reset
      migrate:rollback
      migrate:status
```

The other commands work, so I'm assuming the migrator package installed correctly. Maybe `:site` is deprecated or something?

**Comment by jasonvarga** [comment]
Those are standard Laravel commands. Looks like you don't have the package installed. Can you try to see if you missed any installation steps?

**Comment by jesseleite** [comment]
Also what is output when you run `php please support:details`?

**Comment by andyra** [comment]
@jesseleite `php please support:details` outputs the following:
```
Statamic 3.0.7 Solo
Laravel 7.28.1
PHP 7.4.10
No addons installed
```

**Comment by jesseleite** [comment]
You should see `statamic/migrator` in that list as an installed addon.  As Jason mentioned, can you see if you missed any of [the installation steps listed here](https://github.com/statamic/migrator#using-the-site-migrator)?

**Comment by andyra** [comment]
@jesseleite Thanks! I had tried to install the migratie addon earlier, but I missed the fact that it failed. Thanks for your help.
