### ISSUE TITLE
Layout field with default specified should be renamed or removed on migrate

### ISSUE THREAD

**Issue by fitzage** [statamic/migrator#68]
I had one page which, for whatever reason, had a layout field with the default layout specified, like `layout: default`.

Because the default layout is renamed to layout instead of default, this resulted in no layout actually being selected, and just the template content being sent to the browser (so there was no header, css, or anything that would normally be pulled in by the layout).

I’m not sure why I originally did this, but I’m probably not the only one. It would be nice if the migrator was smart enough to correct for this, either by changing the field to `layout: layout`, or by removing it altogether.

**Comment by jesseleite** [comment]
Indeed, good find!
