### ISSUE TITLE
Unpublished pages from default site are being migrated as published

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/migrator#89]
We have a multisite with 3 languages, and only unpublished non-default languages, that differ in published state, are migrated correctly, since they already have a `published: false` variable.
Unpublished pages prefixed with underscore will be migrated as published - that's quite a lot of pages for us :)

**Comment by jasonvarga** [comment]
I would have thought we would have been handling that. But if not, good catch!

**Comment by FrittenKeeZ** [comment]
@jasonvarga another issue I found, is that the tree structure isn't migrated in the correct order.

Order in v2:
![image](https://user-images.githubusercontent.com/1186125/131970964-4cf8e857-e115-4aac-a2e5-954de4730fa1.png)
![image](https://user-images.githubusercontent.com/1186125/131971439-d2a165d8-2990-4edf-99ff-c171b4912c70.png)

Order in v3:
![image](https://user-images.githubusercontent.com/1186125/131971191-b3563a0b-e29c-4b85-aa2a-0e1a54335bad.png)
![image](https://user-images.githubusercontent.com/1186125/131971544-d47c7823-02ea-45d9-abfc-10490ed5b491.png)

Comwell has quite a lot of pages, so it would be rather cumbersome to fix them all.

**Comment by FrittenKeeZ** [comment]
@jasonvarga although slugs are retained correctly, since we have multiple subpages with the same slug, many pages are responding to a numbered slug like `contact-16`. How can we correct this so the entire site structure remains unaffected and SEO value isn't lost?

**Comment by jesseleite** [comment]
@FrittenKeeZ Published status and entry order should be fixed for multisite migrations on master now.

**Comment by FrittenKeeZ** [comment]
@jesseleite I just tested pages migration again, and the entry structure is still migrated in the wrong order.

**Comment by FrittenKeeZ** [comment]
@jesseleite I found the missing link - sort order wasn't set to be using natural ordering.
```php
->sortBy(function ($folder) {
    return str_replace('/_', '/', $folder);
}, SORT_NATURAL)
```

**Comment by jesseleite** [comment]
Good find, thank you @FrittenKeeZ!
