### ISSUE TITLE
Slugs aren't retained correctly for nested pages, breaking original URLs

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/migrator#97]
Migrated slugs aren't respecting the tree structure, so you can end up with a page in v2 with the URL `/restaurant` being migrated to `/restaurant-14`, causing the original URL to return 404. This will have a huge impact on SEO.

![Skærmbillede 2021-10-21 kl  16 28 09](https://user-images.githubusercontent.com/1186125/138299012-6138b648-deb9-4a8a-b9e7-e21fc8c490a1.png)

**Comment by jesseleite** [comment]
@FrittenKeeZ No problem. I believe it's fixed in the above commit; Let me know if you still have problems with this after updating the migrator 👍
